### ISSUE TITLE
local .less loader not working

### ISSUE THREAD

**Issue by dabeku** [feitzi/ng2-seed#1]
Probably style-loader missing in webpack.config.js for .less files:
old:
```
{
        test: /\.less$/,
        loaders: ['to-string-loader', 'css-loader', 'less-loader']
},
```
new:
```
{
        test: /\.less$/,
        loaders: ['to-string-loader', 'style-loader', 'css-loader', 'less-loader']
},
```

**Comment by feitzi** [comment]
Hi dabeku,

According to 'style-loader' [documentation](styleUrls: ['./app.component.scss'],)
> Adds CSS to the DOM by injecting a <style> tag

So the style-loader inject your style to a <style> tag in the DOM. But in the Seed Project styles are managed by Angular itself. We use this code:

```
styleUrls: ['./app.component.scss'],
```
So injection of the app.component.scss result  to the DOM  isn't required.
